services:
  power-generator:
    container_name: power-generator
    image: power-generator
    build:
      context: .
      dockerfile: Dockerfile-generator
    volumes:
      - ./power-consumption-generator/input:/app/input
    networks:
      - kafka-net
    environment:
      OUTPUT_TOPIC: "input-power"
      DEAD_LETTER_QUEUE: "dlq"
      INPUT_FILE_PATH: "input/power_consumption_data.txt"
    depends_on:
      - power-processor

  power-processor:
    container_name: power-processor
    image: power-processor
    build:
      context: .
      dockerfile: Dockerfile-processor
    networks:
      - kafka-net
    environment:
      INPUT_TOPIC: "input-power"
      OUTPUT_TOPIC: "power-anomalies"
      SIGMA_COEFFICIENT: "5.0"
      APP_ID: "power-consumption-processor"
    depends_on:
      - power-anomalies-consumer

  power-anomalies-consumer:
    container_name: power-anomalies-consumer
    image: power-anomalies-consumer
    build:
      context: .
      dockerfile: Dockerfile-anomaly-consumer
    networks:
      - kafka-net
    environment:
      INPUT_TOPIC: "power-anomalies"
      APP_ID: "power-anomalies-consumer"

networks:
  kafka-net:
    name: kafka-net
    driver: bridge