# Stage 1: Build the application
FROM gradle:8.13.0-jdk17-alpine AS build
WORKDIR /app

# Copy the Gradle wrapper and build files
COPY gradlew .
COPY gradle ./gradle

# Copy the build configuration and source code
COPY ./power-consumption-commons ./power-consumption-commons
COPY ./power-consumption-processor ./power-consumption-processor
COPY settings.gradle ./

# Build the application
RUN ./gradlew clean bootJar

# Stage 2: Create the runtime image
FROM openjdk:17-jdk-slim
WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/power-consumption-processor/build/libs/*.jar processor-power-consumption.jar

ENV INPUT_TOPIC="input-power"
ENV OUTPUT_TOPIC="power-anomalies"
ENV BOOTSTRAP_SERVERS="broker-1:19092, broker-2:19092, broker-3:19092"
ENV SIGMA_COEFFICIENT="2.7"
ENV APP_ID="power-consumption-processor"

# Run the application
ENTRYPOINT ["java", "-jar", "processor-power-consumption.jar"]